Dependencies on external file
conda-forge/r-climate4r-feedstock pull request #1
Opened 2024-01-08 18:45 UTC by cofinoa

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

2024-01-08 18:59 UTC, cofinoa commented
@conda-forge-admin, please rerender

2024-01-08 19:09 UTC, cofinoa commented
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I wanted to let you know that I linted all conda-recipes in your PR (`recipe`) and found some lint.
> 
> Here's what I've got...
> 
> For **recipe**:
> 
> * Failed to even lint the recipe, probably because of a conda-smithy bug 😢. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint .` from the recipe directory.

This relates to conda-forge/wecopttool-feedstock#8

2024-01-09 16:38 UTC, cofinoa commented
@conda-forge-admin, please rerender

2024-01-09 17:55 UTC, mfansler requested changes
This is nonstandard and unmotivated. Please provided an explanation what this is trying to fix.

2025-09-15 12:17 UTC, closed without merging